# -*- coding: utf-8 -*-
"""week3_a108260028_王力瑋.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fWNp7ShkTMCusGIPWR9niY4Fm-YVKRuI
"""

print(“Hello World”)

