# -*- coding: utf-8 -*-
"""week3.a108260028.王力瑋.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgewUTqXQcKPTM-0yujMyhNmZBYbUitN
"""

print(“Hello World”)

!nvidia-smi

